cxx_library (
	name = 'gtest',
	visibility = ['//...'],
	srcs = [
		'googletest/googletest/src/gtest-all.cc',
		'googletest/googletest/src/gtest_main.cc',
	],
	exported_headers = {
		'gtest/gtest-death-test.h' : 'googletest/googletest/include/gtest/gtest-death-test.h',
		'gtest/gtest-message.h' : 'googletest/googletest/include/gtest/gtest-message.h',
		'gtest/gtest-param-test.h' : 'googletest/googletest/include/gtest/gtest-param-test.h',
		'gtest/gtest-printers.h' : 'googletest/googletest/include/gtest/gtest-printers.h',
		'gtest/gtest-spi.h' : 'googletest/googletest/include/gtest/gtest-spi.h',
		'gtest/gtest-test-part.h' : 'googletest/googletest/include/gtest/gtest-test-part.h',
		'gtest/gtest-typed-test.h' : 'googletest/googletest/include/gtest/gtest-typed-test.h',
		'gtest/gtest.h' : 'googletest/googletest/include/gtest/gtest.h',
		'gtest/gtest_pred_impl.h' : 'googletest/googletest/include/gtest/gtest_pred_impl.h',
		'gtest/gtest_prod.h' : 'googletest/googletest/include/gtest/gtest_prod.h',
		'gtest/internal/custom/gtest-port.h' : 'googletest/googletest/include/gtest/internal/custom/gtest-port.h',
		'gtest/internal/custom/gtest-printers.h' : 'googletest/googletest/include/gtest/internal/custom/gtest-printers.h',
		'gtest/internal/custom/gtest.h' : 'googletest/googletest/include/gtest/internal/custom/gtest.h',
		'gtest/internal/gtest-death-test-internal.h' : 'googletest/googletest/include/gtest/internal/gtest-death-test-internal.h',
		'gtest/internal/gtest-filepath.h' : 'googletest/googletest/include/gtest/internal/gtest-filepath.h',
		'gtest/internal/gtest-internal.h' : 'googletest/googletest/include/gtest/internal/gtest-internal.h',
		'gtest/internal/gtest-linked_ptr.h' : 'googletest/googletest/include/gtest/internal/gtest-linked_ptr.h',
		'gtest/internal/gtest-param-util-generated.h' : 'googletest/googletest/include/gtest/internal/gtest-param-util-generated.h',
		'gtest/internal/gtest-param-util.h' : 'googletest/googletest/include/gtest/internal/gtest-param-util.h',
		'gtest/internal/gtest-port-arch.h' : 'googletest/googletest/include/gtest/internal/gtest-port-arch.h',
		'gtest/internal/gtest-port.h' : 'googletest/googletest/include/gtest/internal/gtest-port.h',
		'gtest/internal/gtest-string.h' : 'googletest/googletest/include/gtest/internal/gtest-string.h',
		'gtest/internal/gtest-tuple.h' : 'googletest/googletest/include/gtest/internal/gtest-tuple.h',
		'gtest/internal/gtest-type-util.h' : 'googletest/googletest/include/gtest/internal/gtest-type-util.h',
	},
	headers = {
		'src/gtest-death-test.cc' : 'googletest/googletest/src/gtest-death-test.cc',
		'src/gtest-filepath.cc' : 'googletest/googletest/src/gtest-filepath.cc',
		'src/gtest-port.cc' : 'googletest/googletest/src/gtest-port.cc',
		'src/gtest-printers.cc' : 'googletest/googletest/src/gtest-printers.cc',
		'src/gtest-test-part.cc' : 'googletest/googletest/src/gtest-test-part.cc',
		'src/gtest-typed-test.cc' : 'googletest/googletest/src/gtest-typed-test.cc',
		'src/gtest.cc' : 'googletest/googletest/src/gtest.cc',
		'src/gtest-internal-inl.h' : 'googletest/googletest/src/gtest-internal-inl.h',
	},
)
