cxx_library (
	name = 'proposal',
	header_namespace = 'proposed',
	exported_headers = {
		'base-hack.h': 'base-hack.h',
		'common-hacky-helpers.h': 'common-hacky-helpers.h',
		'map': 'map.h',
		'multimap': 'multimap.h',
		'multiset': 'multiset.h',
		'set': 'set.h',
	},
	visibility = [
    	'PUBLIC',
  	],
	deps = [
		'//general:proposal',
	],
)
