cxx_library (
	name = 'copy',
	exported_headers = [
		'copy.h',
	],
)

cxx_test (
	name = 'MapTest',
	srcs = [
		'MapTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		':copy',
	],
)

cxx_test (
	name = 'MultiMapTest',
	srcs = [
		'MultiMapTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
	],
)

cxx_test (
	name = 'MultiSetTest',
	srcs = [
		'MultiSetTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		':copy',
	],
)

cxx_test (
	name = 'SetTest',
	srcs = [
		'SetTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		':copy',
	],
)
