cxx_test (
	name = 'MapTest',
	srcs = [
		'MapTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		'//test-utils:copy',
		'//general:proposal',
	],
)

cxx_test (
	name = 'MultiMapTest',
	srcs = [
		'MultiMapTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		'//general:proposal',
	],
)

cxx_test (
	name = 'MultiSetTest',
	srcs = [
		'MultiSetTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		'//test-utils:copy',
		'//general:proposal',
	],
)

cxx_test (
	name = 'SetTest',
	srcs = [
		'SetTest.cpp',
	],
	deps = [
		'//equivalent-ordered:proposal',
		'//test-utils:copy',
		'//general:proposal',
	],
)
